# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

dev:
  propel:
    param:
      classname:  DebugPDO
      debug:
        realmemoryusage: true
        details:
          time:       { enabled: true }
          slow:       { enabled: true, threshold: 0.1 }
          mem:        { enabled: true }
          mempeak:    { enabled: true }
          memdelta:   { enabled: true }

test:
  main:
     param:
       classname: DebugPDO

all:    
  propel: 
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=dota_resource;host=<?php echo AzulServerEnv::getInstance()->get('main_db_host')."\n"; ?>
      username:   <?php echo AzulServerEnv::getInstance()->get('main_db_user')."\n"; ?>
      password:   <?php echo AzulServerEnv::getInstance()->get('main_db_pass')."\n"; ?>
      encoding:   utf8
      persistent: true
      pooling:    true
