local:
  main_db_host: '192.168.1.120'
  main_db_user: 'root'
  main_db_pass: ''
  main_db_name: 'dota_resource'
  

staging:
  main_db_host: '192.168.1.120'
  main_db_user: 'hq_main_user'
  main_db_pass: 'hq_main_user'
  main_db_name: 'hq_main'
  
production:
  main_db_host: '192.168.1.120'
  main_db_user: 'hq_main_user'
  main_db_pass: 'hq_main_user'
  main_db_name: 'hq_main'